"""roles

Revision ID: 820ced56be79
Revises: 496377b1d8e5
Create Date: 2025-03-24 14:40:38.239173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820ced56be79'
down_revision: Union[str, None] = '496377b1d8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('is_aproved', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['owner_id'], ['id'])
    op.add_column('locations', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('is_aproved', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'locations', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'is_aproved')
    op.drop_column('locations', 'owner_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'is_aproved')
    op.drop_column('comments', 'owner_id')
    # ### end Alembic commands ###
